### ISSUE TITLE
Unset Id doesn't work with let

### ISSUE THREAD

**Issue by coddra** [darrenks/atlas#2]
# Problem
The unset id feature combined with let gives an internal atlas error.

# Example

## Input:

```
a@b,b
```

## Expected output

```
aa
```

`stderr`:
```
1:1 (a) unset identifier "a" (Warning)
```

## Actual output

```
```

`stderr`:
```
1:1 (a) unset identifier "a" (Warning)
!!!This is an internal Altas error, please report the bug (via github issue or email name of this lang at golfscript.com)!!!

/home/coddra/Code/Build/atlas/ir.rb:118:in `lookup_vars': undefined method `id' for nil:NilClass (NoMethodError)
	from /home/coddra/Code/Build/atlas/ir.rb:123:in `lookup_vars'
	from /home/coddra/Code/Build/atlas/ir.rb:120:in `block in lookup_vars'
	from /home/coddra/Code/Build/atlas/ir.rb:120:in `map!'
	from /home/coddra/Code/Build/atlas/ir.rb:120:in `lookup_vars'
	from /home/coddra/Code/Build/atlas/ir.rb:63:in `to_ir'
	from /home/coddra/Code/Build/atlas/repl.rb:81:in `block in repl'
	from /home/coddra/Code/Build/atlas/repl.rb:66:in `each'
	from /home/coddra/Code/Build/atlas/repl.rb:66:in `repl'
	from /home/coddra/Code/Build/atlas/atlas:14:in `<main>'
```

# Proof of the problem's origin

Replacing `a` with `'a` solves the problem, even though `a`, if not set, should default to the value `'a`.

# Note

This language is genius, thank you very much!

**Comment by darrenks** [comment]
Hi coddra,

Thanks for reporting this and your kind words :) I'll fix this
